Repository updatecli/updatecli, pull requests merged in 2020-11, with the labels that each got.

#115 Return false when wrong yaml condition
  pkg/plugins/yaml/condition.go
Labels: bug

#117 upload assets on published release
  .github/workflows/publish-assets.yaml
  utils/build.sh
Labels: enhancement

#119 Update contributing.adoc
  doc/CONTRIBUTING.adoc
Labels: documentation

#120 Improve support for non dockerhub registries
  .github/workflows/go.yaml
  doc/README.adoc
  pkg/plugins/docker/condition.go
  pkg/plugins/docker/main.go
  pkg/plugins/docker/main_test.go
  pkg/plugins/docker/quayio.go
  pkg/plugins/docker/registry/dockerhub/main.go
  pkg/plugins/docker/registry/dockerhub/main_test.go
  pkg/plugins/docker/registry/dockerregistry/main.go
  pkg/plugins/docker/registry/dockerregistry/main_test.go
  pkg/plugins/docker/registry/ghcr/main.go
  pkg/plugins/docker/registry/ghcr/main_test.go
  pkg/plugins/docker/registry/quay/main.go
  pkg/plugins/docker/registry/quay/main_test.go
  pkg/plugins/docker/source.go
Labels: enhancement

#121 Update docker registry documentation
  doc/README.adoc
Labels: documentation

#125 Correctly retrieve docker image digest from ghcr.io.
  pkg/plugins/docker/condition.go
  pkg/plugins/docker/main.go
  pkg/plugins/docker/main_test.go
  pkg/plugins/docker/registry/dockerregistry/main.go
  pkg/plugins/docker/registry/ghcr/main.go
  pkg/plugins/docker/registry/ghcr/main_test.go
  pkg/plugins/docker/source.go
Labels: bug
