Repository updatecli/updatecli, pull requests merged in 2020-07, with the labels that each got.

#55 trigger on pull requests as well
  .github/workflows/go.yaml
Labels: enhancement

#54 make title and message pretty
  pkg/engine/target/main.go
  pkg/git/main.go
  pkg/github/main.go
  pkg/scm/main.go
  pkg/yaml/main.go
Labels: enhancement

#56 Add support for array in Target yaml key
  README.md
  pkg/yaml/main.go
  pkg/yaml/main_test.go
Labels: enhancement

#57 Checkout locally to remoteBranch value
  pkg/github/main.go
Labels: bug

#58 Fix apply parameters
  cmd/apply.go
Labels: bug

#62 Only use prefix/postfix when updating target
  README.md
  pkg/engine/main.go
  pkg/engine/source/main.go
  pkg/engine/target/main.go
Labels: enhancement

#65 Use YAML in condition as well
  pkg/engine/condition/main.go
  pkg/engine/target/main.go
  pkg/scm/main.go
  pkg/yaml/main.go
  updateCli.d/grafana-loki.tpl
  updateCli.d/jenkins-chart.tpl
  updateCli.d/noYamlConditionScm.tpl
Labels: enhancement

#64 Add helm chart source message
  pkg/helm/chart/main.go
Labels: bug

#66 Github release return release tag_name instead name
  pkg/github/main.go
Labels: bug

#69 Build binary for Windows/Mac/Linux
  Makefile
  utils/build.sh
Labels: enhancement

#68 Fetch every branches from git
  pkg/git/generic/main.go
  pkg/git/main.go
  pkg/github/main.go
Labels: bug

#72 Sanitize git branch name
  pkg/git/generic/main.go
  pkg/git/generic/main_test.go
  pkg/git/main.go
  pkg/github/main.go
Labels: bug

#73 Search yaml target file into multiple location
  examples/updateCli.d/docker-compose.yaml
  pkg/engine/target/main.go
Labels: enhancement

#74 Diff don't change target files
  cmd/apply.go
  cmd/diff.go
  cmd/root.go
  pkg/engine/main.go
  pkg/engine/target/main.go
  pkg/engine/target/options.go
  pkg/yaml/main.go
Labels: bug

#76 Issues/319 Corretly set working directory
  pkg/engine/condition/main.go
  pkg/engine/target/main.go
Labels: bug

#77 Update documentation
  ADOPTERS.md
  CONTRIBUTING.md
  README.md
Labels: documentation

#78 Improve README.md
  README.md
Labels: documentation

#81 Update docker-compose.adoc
  doc/scenarios/docker-compose.adoc
Labels: documentation

#82 Add replace rules in source definition
  README.md
  pkg/engine/source/main.go
  pkg/engine/source/replacer.go
  pkg/engine/source/replacer_test.go
Labels: enhancement

#83 Add docker registry v2 support
  pkg/docker/main.go
Labels: enhancement

#84 Add Reports summary
  cmd/root.go
  pkg/config/main.go
  pkg/docker/main_test.go
  pkg/engine/condition/main.go
  pkg/engine/main.go
  pkg/engine/source/main.go
  pkg/engine/target/main.go
  pkg/reports/main.go
  pkg/reports/report.go
  pkg/reports/stage.go
  pkg/result/main.go
Labels: enhancement
