Repository updatecli/updatecli, pull requests merged in 2021-03, with the labels that each got.

#185 Update GitHub Pull Request Format
  pkg/plugins/github/pullrequest.go
Labels: enhancement

#186 Start using Sementatic Versioning
  .github/release-drafter.yaml
Labels: enhancement

#191 Improve pull request manipulation scenarios
  pkg/core/engine/target/main.go
Labels: bug

#190 Fix Docker Build/Push
  .github/workflows/publish-docker-image.yaml
  Dockerfile
  Makefile
Labels: bug

#193 config checksum should not consider templated values
  pkg/core/config/checksum.example
  pkg/core/config/main.go
  pkg/core/config/main_test.go
Labels: bug

#194 Add helmChart target
  examples/updateCli.generic/helmChart/SCM.tpl
  examples/updateCli.generic/helmChart/noSCM.yaml
  examples/updateCli.generic/helmChart/requirement.tpl
  examples/updateCli.generic/jenkins/.stable.tpl.swp
  go.mod
  go.sum
  pkg/core/engine/target/main.go
  pkg/plugins/helm/chart/changelog.go
  pkg/plugins/helm/chart/main.go
  pkg/plugins/helm/chart/target.go
Labels: enhancement, target

#195 Don't differentiate yaml/tpl updatecli config
  pkg/core/config/main.go
  pkg/plugins/helm/chart/changelog.go
Labels: enhancement

#183 Add multi sources support
  examples/updateCli.d/sources/dockerfile_sources.tpl
  pkg/core/config/main.go
  pkg/core/config/template.go
  pkg/core/engine/condition/main.go
  pkg/core/engine/main.go
  pkg/core/engine/target/main.go
  pkg/core/reports/main.go
  pkg/core/reports/report.go
Labels: enhancement

#197 Simplify helmchart incremental chart version configuration
  examples/updateCli.generic/helmChart/SCM.tpl
  examples/updateCli.generic/helmChart/noSCM.yaml
  examples/updateCli.generic/helmChart/requirement.tpl
  pkg/plugins/helm/chart/main.go
  pkg/plugins/helm/chart/target.go
Labels: enhancement

#196 Add version pattern for Github Source and correctly handle github tags
  examples/updateCli.generic/githubRelease.tpl
  pkg/plugins/github/changelog.go
  pkg/plugins/github/main.go
  pkg/plugins/github/pageInfo.go
  pkg/plugins/github/rateLimit.go
  pkg/plugins/github/scm.go
  pkg/plugins/github/source.go
  pkg/plugins/github/source_test.go
  pkg/plugins/helm/chart/source.go
  pkg/plugins/version/main.go
  pkg/plugins/version/main_test.go
  pkg/plugins/version/semver/main.go
  pkg/plugins/version/semver/main_test.go
Labels: enhancement, source

#200 Add dependabot configuration
  .github/dependabot.yaml
Labels: enhancement

#202 Update to Go 1.16
  .github/workflows/go.yaml
  .github/workflows/publish-assets.yaml
  .goreleaser.yml
  Dockerfile
  doc/CONTRIBUTING.adoc
  go.mod
Labels: enhancement
