Repository updatecli/updatecli, pull requests merged in 2021-01, with the labels that each got.

#135 Add dockerfile support for Source,Condtion,Target
  doc/README.adoc
  examples/updateCli.d/dockerfile.tpl
  examples/updateCli.d/updateCli.tpl
  examples/updateCli.generic/dockerfile.tpl
  examples/updateCli.generic/maven.yaml
  go.mod
  go.sum
  pkg/core/engine/condition/main.go
  pkg/core/engine/main.go
  pkg/core/engine/target/main.go
  pkg/core/helpers/main.go
  pkg/plugins/docker/dockerfile/condition.go
  pkg/plugins/docker/dockerfile/main.go
  pkg/plugins/docker/dockerfile/main_test.go
  pkg/plugins/docker/dockerfile/marshal.go
  pkg/plugins/docker/dockerfile/marshal_test.go
  pkg/plugins/docker/dockerfile/target.go
  pkg/plugins/helm/chart/changelog.go
  pkg/plugins/helm/chart/main_test.go
Labels: documentation, enhancement

#138 Add source YAML
  pkg/core/engine/main.go
  pkg/core/engine/source/main.go
  pkg/plugins/docker/main_test.go
  pkg/plugins/docker/source.go
  pkg/plugins/github/source.go
  pkg/plugins/helm/chart/main_test.go
  pkg/plugins/helm/chart/source.go
  pkg/plugins/maven/main_test.go
  pkg/plugins/maven/source.go
  pkg/plugins/yaml/source.go
Labels: enhancement

#139 Add resource file
  examples/updateCli.generic/file.tpl
  pkg/core/engine/condition/main.go
  pkg/core/engine/main.go
  pkg/core/engine/source/main.go
  pkg/core/engine/target/main.go
  pkg/plugins/file/condition.go
  pkg/plugins/file/helpers.go
  pkg/plugins/file/main.go
  pkg/plugins/file/source.go
  pkg/plugins/file/target.go
Labels: enhancement

#140 Add hidden command to generate markdown documentation
  cmd/docs.go
  cmd/root.go
Labels: documentation

#141 Yaml resource can read file from http url
  pkg/core/engine/main.go
  pkg/plugins/file/condition.go
  pkg/plugins/file/helpers.go
  pkg/plugins/file/source.go
  pkg/plugins/file/target.go
  pkg/plugins/yaml/condition.go
  pkg/plugins/yaml/main.go
  pkg/plugins/yaml/source.go
  pkg/plugins/yaml/target.go
Labels: enhancement

#143 Add docker.io as an alias for dockerhub registry
  pkg/plugins/docker/main.go
Labels: bug

#142 Don't systematically run the prepare stage
  cmd/root.go
Labels: bug

#147 chore: add error handling around reported areas from golangci-lint
  .golangci.yml
  cmd/root.go
  pkg/core/config/template.go
  pkg/core/engine/condition/main.go
  pkg/core/engine/main.go
  pkg/core/engine/target/main.go
  pkg/core/helpers/main.go
  pkg/core/scm/main.go
  pkg/core/version/main.go
  pkg/plugins/docker/dockerfile/marshal.go
  pkg/plugins/docker/dockerfile/marshal_test.go
  pkg/plugins/docker/dockerfile/target.go
  pkg/plugins/docker/main_test.go
  pkg/plugins/docker/registry/dockerhub/main.go
  pkg/plugins/docker/registry/dockerregistry/main.go
  pkg/plugins/docker/registry/ghcr/main.go
  pkg/plugins/docker/registry/quay/main.go
  pkg/plugins/docker/registry/quay/main_test.go
  pkg/plugins/file/helpers.go
  pkg/plugins/git/scm.go
  pkg/plugins/github/changelog.go
  pkg/plugins/helm/chart/condition.go
  pkg/plugins/maven/condition.go
  pkg/plugins/maven/source.go
Labels: bug

#148 Fix various regression
  pkg/plugins/docker/registry/dockerhub/main_test.go
  pkg/plugins/docker/registry/dockerregistry/main.go
  pkg/plugins/docker/registry/ghcr/main.go
  pkg/plugins/docker/registry/quay/main.go
  pkg/plugins/github/main.go
  pkg/plugins/github/pullrequest.go
  pkg/plugins/yaml/target.go
Labels: bug

#151 Display a specific message when no changelog available from a Github Release
  pkg/plugins/github/changelog.go
  pkg/plugins/github/main.go
Labels: enhancement

#150 Add prefix/postfix to condition stage
  pkg/core/engine/condition/main.go
  pkg/core/engine/main.go
Labels: enhancement

#163 Better Handle errors
  cmd/apply.go
  cmd/diff.go
  cmd/prepare.go
  cmd/root.go
  cmd/show.go
  pkg/core/config/template.go
  pkg/core/reports/main.go
  pkg/plugins/git/generic/main.go
Labels: bug

#149 [source][condition] Add Jenkins resource [source,condition]
  examples/updateCli.generic/jenkins/.stable.tpl.swp
  examples/updateCli.generic/jenkins/stable.tpl
  examples/updateCli.generic/jenkins/weekly.tpl
  go.mod
  pkg/core/engine/condition/main.go
  pkg/core/engine/source/main.go
  pkg/plugins/jenkins/changelog.go
  pkg/plugins/jenkins/condition.go
  pkg/plugins/jenkins/main.go
  pkg/plugins/jenkins/main_test.go
  pkg/plugins/jenkins/semver.go
  pkg/plugins/jenkins/semver_test.go
  pkg/plugins/jenkins/source.go
Labels: enhancement

#164 Remove syscall
  pkg/plugins/yaml/target.go
Labels: bug

#165 Read configurations before showing them
  pkg/core/engine/main.go
Labels: bug

#166 Improving linting and building test from GH Action
  .github/workflows/go.yaml
  Makefile
  cmd/version.go
  pkg/core/config/main.go
  pkg/core/engine/main.go
  pkg/core/engine/source/main.go
  pkg/core/engine/target/main.go
  pkg/core/log/format.go
  pkg/core/reports/main.go
  pkg/core/reports/report.go
  pkg/core/version/main.go
  pkg/plugins/docker/condition.go
  pkg/plugins/docker/dockerfile/condition.go
  pkg/plugins/docker/dockerfile/main.go
  pkg/plugins/docker/dockerfile/main_test.go
  pkg/plugins/docker/dockerfile/marshal_test.go
  pkg/plugins/docker/dockerfile/target.go
  pkg/plugins/docker/main.go
  pkg/plugins/docker/main_test.go
  pkg/plugins/docker/registry/dockerhub/main_test.go
  pkg/plugins/docker/registry/dockerregistry/main_test.go
  pkg/plugins/docker/registry/ghcr/main_test.go
  pkg/plugins/docker/registry/quay/main_test.go
  pkg/plugins/docker/source.go
  pkg/plugins/file/condition.go
  pkg/plugins/file/target.go
  pkg/plugins/git/main.go
  pkg/plugins/git/scm.go
  pkg/plugins/github/changelog.go
  pkg/plugins/github/main.go
  pkg/plugins/github/pullrequest.go
  pkg/plugins/github/scm.go
  pkg/plugins/github/source.go
  pkg/plugins/helm/chart/changelog.go
  pkg/plugins/helm/chart/condition.go
  pkg/plugins/helm/chart/source.go
  pkg/plugins/maven/condition.go
  pkg/plugins/maven/source.go
  pkg/plugins/yaml/condition.go
  pkg/plugins/yaml/main.go
  pkg/plugins/yaml/main_test.go
  pkg/plugins/yaml/source.go
Labels: enhancement
