Repository updatecli/updatecli, pull requests merged in 2021-09, with the labels that each got.

#270 Automate Golang and Goreleaser using updatecli
  .github/workflows/go.yaml
  .github/workflows/release-sandbox.yaml
  .github/workflows/release.yaml
  .github/workflows/updatecli.yaml
  Dockerfile
  updatecli/updatecli.d/golang.yaml
  updatecli/updatecli.d/gorelease.yaml
Labels: github_actions

#271 Fix golang version automated update
  updatecli/updatecli.d/golang.yaml
  updatecli/updatecli.d/gorelease.yaml
Labels: bug

#275 Fixes links to adopter/contributing docs
  README.adoc
Labels: documentation
