Repository updatecli/updatecli, pull requests merged in 2021-10, with the labels that each got.

#265 Add a new resource to manipulate AWS AMI
  .github/workflows/go.yaml
  examples/updateCli.generic/aws_ami.yaml
  go.mod
  go.sum
  pkg/core/engine/condition/main.go
  pkg/core/engine/source/main.go
  pkg/plugins/aws/ami/condition.go
  pkg/plugins/aws/ami/condition_test.go
  pkg/plugins/aws/ami/data_test.go
  pkg/plugins/aws/ami/filter.go
  pkg/plugins/aws/ami/helpers.go
  pkg/plugins/aws/ami/helpers_test.go
  pkg/plugins/aws/ami/main.go
  pkg/plugins/aws/ami/sort.go
  pkg/plugins/aws/ami/source.go
  pkg/plugins/aws/ami/source_test.go
  pkg/plugins/aws/ami/spec.go
Labels: enhancement, source, condition, resource-aws-ami

#292 Update sops version to v3 to support go module
  go.mod
  go.sum
  pkg/core/config/template.go
Labels: dependencies

#302 chore: fix homebrew publication
  .github/workflows/release-sandbox.yaml
  .github/workflows/release.yaml
  .goreleaser.yml
Labels: bug
