Repository updatecli/updatecli, pull requests merged in 2021-08, with the labels that each got.

#259 Various tidy up
  .goreleaser.yml
  ADOPTERS.md
  CONTRIBUTING.adoc
  README.adoc
  cmd/root.go
  cmd/version.go
  doc/README.adoc
  doc/scenarios/docker-compose.adoc
  go.mod
  main.go
  pkg/core/config/main.go
  pkg/core/config/main_test.go
  pkg/core/context/main.go
  pkg/core/engine/condition/main.go
  pkg/core/engine/conditions.go
  pkg/core/engine/main.go
  pkg/core/engine/options.go
  pkg/core/engine/sort.go
  pkg/core/engine/sort_test.go
  pkg/core/engine/source/main.go
  pkg/core/engine/sources.go
  pkg/core/engine/target/main.go
  pkg/core/engine/targets.go
  pkg/core/reports/main.go
  pkg/core/reports/report.go
  pkg/core/scm/main.go
  pkg/plugins/docker/condition.go
  pkg/plugins/docker/dockerfile/condition.go
  pkg/plugins/docker/dockerfile/condition_test.go
  pkg/plugins/docker/dockerfile/main.go
  pkg/plugins/docker/dockerfile/main_test.go
  pkg/plugins/docker/dockerfile/mobyparser/main.go
  pkg/plugins/docker/dockerfile/simpletextparser/main.go
  pkg/plugins/docker/dockerfile/simpletextparser/main_test.go
  pkg/plugins/docker/dockerfile/target.go
  pkg/plugins/docker/dockerfile/target_test.go
  pkg/plugins/docker/source.go
  pkg/plugins/file/condition.go
  pkg/plugins/file/target.go
  pkg/plugins/git/main.go
  pkg/plugins/git/scm.go
  pkg/plugins/git/tag/condition.go
  pkg/plugins/git/tag/main.go
  pkg/plugins/git/tag/source.go
  pkg/plugins/git/tag/target.go
  pkg/plugins/github/main.go
  pkg/plugins/github/scm.go
  pkg/plugins/helm/chart/condition.go
  pkg/plugins/helm/chart/target.go
  pkg/plugins/jenkins/changelog.go
  pkg/plugins/jenkins/condition.go
  pkg/plugins/jenkins/main.go
  pkg/plugins/maven/condition.go
  pkg/plugins/version/main.go
  pkg/plugins/yaml/condition.go
  pkg/plugins/yaml/source.go
  pkg/plugins/yaml/target.go
Labels: documentation

#264 Add a new resource of type "shell"
  examples/updateCli.generic/shell/condition.sh
  examples/updateCli.generic/shell/shell.yaml
  examples/updateCli.generic/shell/source.sh
  examples/updateCli.generic/shell/target.sh
  pkg/core/engine/condition/main.go
  pkg/core/engine/source/main.go
  pkg/core/engine/target/main.go
  pkg/plugins/shell/command.go
  pkg/plugins/shell/command_test.go
  pkg/plugins/shell/condition.go
  pkg/plugins/shell/condition_test.go
  pkg/plugins/shell/errors.go
  pkg/plugins/shell/main.go
  pkg/plugins/shell/main_test.go
  pkg/plugins/shell/source.go
  pkg/plugins/shell/source_test.go
  pkg/plugins/shell/target.go
  pkg/plugins/shell/target_test.go
Labels: enhancement, target, source, condition

#269 bugfix: correct error report when using a shell resource (inverting stdout and stderr)
  pkg/plugins/shell/errors.go
Labels: bug, target, source, condition
