Repository updatecli/updatecli, pull requests merged in 2022-04, with the labels that each got.

#611 Deprecate scmID in favor of scmid
  e2e/skipped.targets.d/multiple-conditions.yaml
  e2e/skipped.targets.d/one-condition.yaml
  e2e/updatecli.d/jenkins.yaml
  e2e/updatecli.d/source/gitTag.yaml
  pkg/core/config/main.go
  pkg/core/config/main_test.go
  pkg/core/pipeline/condition/main.go
  pkg/core/pipeline/pullrequest/main.go
  pkg/core/pipeline/resource/main.go
  pkg/core/pipeline/source/main.go
  pkg/core/pipeline/target/main.go
Labels: deprecated

#615 Add various spec comment and fix small linting issues
  pkg/plugins/resources/awsami/condition.go
  pkg/plugins/resources/awsami/filter.go
  pkg/plugins/resources/awsami/helpers.go
  pkg/plugins/resources/awsami/main.go
  pkg/plugins/resources/awsami/source.go
  pkg/plugins/resources/awsami/spec.go
  pkg/plugins/resources/dockerdigest/main.go
  pkg/plugins/resources/dockerdigest/source.go
  pkg/plugins/resources/dockerfile/condition.go
  pkg/plugins/resources/dockerfile/condition_test.go
  pkg/plugins/resources/dockerfile/main.go
  pkg/plugins/resources/dockerfile/main_test.go
  pkg/plugins/resources/dockerimage/condition.go
  pkg/plugins/resources/dockerimage/main.go
Labels: skip-changelog

#587 Add updatecli subcommand to generate json schema
  .gitignore
  cmd/jsonschema.go
  cmd/root.go
  go.mod
  go.sum
  pkg/core/engine/main.go
  pkg/core/jsonschema/main.go
  pkg/core/jsonschema/main_test.go
  pkg/core/pipeline/condition/main.go
  pkg/core/pipeline/pullrequest/main.go
  pkg/core/pipeline/resource/main.go
  pkg/core/pipeline/scm/main.go
  pkg/core/pipeline/source/main.go
  pkg/core/pipeline/target/main.go
  pkg/plugins/resources/awsami/spec.go
Labels: enhancement

#633 fix: return list of modified files for targets of kind: file
  pkg/plugins/resources/file/target.go
  pkg/plugins/resources/file/target_test.go
Labels: bug, resource-file

#636 fix: return an error when no file has been changed
  pkg/core/pipeline/target/main.go
Labels: bug, target

#626 Update updatecli manifest for version v0.23.1
  e2e/updatecli.d/maven.yaml
  e2e/updatecli.d/source/gitTag.yaml
  e2e/updatecli.d/source/githubRelease.2.yaml
  e2e/updatecli.d/source/githubRelease.yaml
  examples/updatecli.d/docker-compose.yaml
  examples/updatecli.d/dockerfile.yaml
  examples/updatecli.d/grafana-loki.yaml
  examples/updatecli.d/jenkins-chart.yaml
  examples/updatecli.d/jenkins-wiki-exporter.yaml
  examples/updatecli.d/jenkins.yaml
  examples/updatecli.d/jenkinsio.yaml
  examples/updatecli.d/nginx.yaml
  examples/updatecli.d/noYamlConditionScm.yaml
  examples/updatecli.d/pluginsite-api.yaml
  examples/updatecli.d/prometheus.yalm
  examples/updatecli.d/prometheus.yaml
  examples/updatecli.d/sources/dockerfile_sources.yaml
  examples/updatecli.d/updatecli.yaml
  updatecli/updatecli.d/golang.yaml
  updatecli/updatecli.d/updatecli.yaml
  updatecli/updatecli.d/venom.yaml
Labels: skip-changelog

#645 fix: use the URL instead of the token to initialize GitHub Enterprise client
  pkg/plugins/scms/github/main.go
Labels: bug

#638 fix: report failure when at least one of the target is failing
  pkg/core/engine/main.go
  pkg/core/pipeline/targets.go
Labels: bug, target

#652 Bump golanci-lint version used in Github Action
  .github/workflows/go.yaml
  Makefile
  updatecli/updatecli.d/golangci-lint.yaml
Labels: dependencies, skip-changelog

#556 Replace example with a video
  README.adoc
Labels: skip-changelog

#658 Adds support for new OCI registries
  pkg/plugins/utils/docker/dockerregistry/main.go
  pkg/plugins/utils/docker/dockerregistry/main_test.go
Labels: enhancement, resource-dockerdigest
