Repository updatecli/updatecli, pull requests merged in 2022-08, with the labels that each got.

#795 Fix: Do not update Helm Chart dependencies in dryrun mode
  pkg/plugins/resources/helm/target.go
Labels: bug, resource-helmchart

#744 feat: Add Gitea support
  .github/workflows/go.yaml
  e2e/updatecli.d/success.d/gitea/branch.yaml
  e2e/updatecli.d/success.d/gitea/release.yaml
  e2e/updatecli.d/success.d/gitea/scm.yaml
  e2e/updatecli.d/success.d/gitea/tag.yaml
  go.mod
  go.sum
  pkg/core/pipeline/pullrequest/main.go
  pkg/core/pipeline/resource/main.go
  pkg/core/pipeline/scm/config.go
  pkg/core/pipeline/scm/main.go
  pkg/core/pipeline/targets.go
  pkg/plugins/resources/gitea/branch/changelog.go
  pkg/plugins/resources/gitea/branch/condition.go
  pkg/plugins/resources/gitea/branch/condition_test.go
  pkg/plugins/resources/gitea/branch/main.go
  pkg/plugins/resources/gitea/branch/source.go
  pkg/plugins/resources/gitea/branch/source_test.go
  pkg/plugins/resources/gitea/branch/target.go
  pkg/plugins/resources/gitea/client/main.go
  pkg/plugins/resources/gitea/pullrequest/main.go
  pkg/plugins/resources/gitea/pullrequest/main_test.go
  pkg/plugins/resources/gitea/release/changelog.go
  pkg/plugins/resources/gitea/release/condition.go
  pkg/plugins/resources/gitea/release/condition_test.go
  pkg/plugins/resources/gitea/release/main.go
  pkg/plugins/resources/gitea/release/source.go
  pkg/plugins/resources/gitea/release/source_test.go
  pkg/plugins/resources/gitea/release/target.go
  pkg/plugins/resources/gitea/release/target_test.go
  pkg/plugins/resources/gitea/tag/changelog.go
  pkg/plugins/resources/gitea/tag/condition.go
  pkg/plugins/resources/gitea/tag/condition_test.go
  pkg/plugins/resources/gitea/tag/main.go
  pkg/plugins/resources/gitea/tag/source.go
  pkg/plugins/resources/gitea/tag/source_test.go
  pkg/plugins/resources/gitea/tag/target.go
  pkg/plugins/scms/gitea/main.go
  pkg/plugins/scms/gitea/scm.go
  pkg/plugins/scms/gitea/util.go
  pkg/plugins/scms/github/main.go
  pkg/plugins/scms/github/main_test.go
  pkg/plugins/utils/version/main.go
  pkg/plugins/utils/version/main_test.go
  pkg/plugins/utils/version/semver.go
  pkg/plugins/utils/version/semver_test.go
Labels: enhancement, scm-gittea

#793 Don't clean temporary updatecli directory by default
  cmd/apply.go
  cmd/diff.go
  cmd/prepare.go
Labels: enhancement

#802 Semver filtering should preserv "v" prefix if specified
  e2e/updatecli.d/success.d/gitea/tag.yaml
  pkg/plugins/resources/gitea/branch/source.go
  pkg/plugins/resources/gitea/release/source.go
  pkg/plugins/resources/gitea/tag/source.go
  pkg/plugins/resources/githubrelease/source.go
  pkg/plugins/resources/gittag/condition.go
  pkg/plugins/resources/gittag/source.go
  pkg/plugins/resources/gittag/target.go
  updatecli/updatecli.d/venom.yaml
Labels: bug

#798 Implement the source "DockerImage"
  e2e/updatecli.d/warning.d/dockerimage.yaml
  e2e/venom.d/test_warning.yaml
  pkg/plugins/resources/dockerimage/main.go
  pkg/plugins/resources/dockerimage/main_test.go
  pkg/plugins/resources/dockerimage/source.go
  pkg/plugins/utils/docker/dockermocks/main.go
  pkg/plugins/utils/docker/dockerregistry/main.go
  pkg/plugins/utils/docker/dockerregistry/tags.go
  pkg/plugins/utils/docker/dockerregistry/tags_test.go
  pkg/plugins/utils/link/main.go
  pkg/plugins/utils/link/main_test.go
Labels: enhancement, resource-docker

#815 feat: add a new 'experimental' flag
  cmd/root.go
  pkg/core/cmdoptions/main.go
Labels: enhancement

#818 Configure Codecov
  .github/workflows/go.yaml
  .gitignore
  Makefile
Labels: skip-changelog

#816 feat: revert #802 and use experimental to control the returned filtered version
  e2e/updatecli.d/success.d/source/gitTag.yaml
  e2e/updatecli.d/warning.d/dockerimage.yaml
  pkg/plugins/resources/dockerimage/source.go
  pkg/plugins/resources/gitea/branch/source.go
  pkg/plugins/resources/gitea/release/source.go
  pkg/plugins/resources/gitea/tag/source.go
  pkg/plugins/resources/githubrelease/source.go
  pkg/plugins/resources/gittag/condition.go
  pkg/plugins/resources/gittag/source.go
  pkg/plugins/resources/gittag/target.go
  pkg/plugins/utils/version/main.go
  pkg/plugins/utils/version/semver.go
Labels: enhancement, experimental

#763 Automate Helm Chart Update
  cmd/apply.go
  cmd/autodiscovery.go
  cmd/diff.go
  cmd/manifest_show.go
  cmd/manifest_upgrade.go
  cmd/prepare.go
  cmd/root.go
  cmd/show.go
  e2e/updatecli.d/warning.d/autodiscovery/fleet/git.yaml
  e2e/updatecli.d/warning.d/autodiscovery/fleet/githubPullrequest.yaml
  e2e/updatecli.d/warning.d/autodiscovery/helm/example.1.yaml
  pkg/core/config/deprecated.go
  pkg/core/config/main.go
  pkg/core/config/main_test.go
  pkg/core/engine/main.go
  pkg/core/pipeline/autodiscovery/config/groupby.go
  pkg/core/pipeline/autodiscovery/config/main.go
  pkg/core/pipeline/autodiscovery/main.go
  pkg/core/pipeline/options.go
  pkg/core/pipeline/pullRequests.go
  pkg/core/pipeline/pullrequest/main.go
  pkg/plugins/autodiscovery/fleet/dependencies.go
  pkg/plugins/autodiscovery/fleet/main.go
  pkg/plugins/autodiscovery/fleet/main_test.go
  pkg/plugins/autodiscovery/fleet/matchingRule.go
  pkg/plugins/autodiscovery/fleet/testdata/fleet.d/grafana/fleet.yaml
  pkg/plugins/autodiscovery/fleet/utils.go
  pkg/plugins/autodiscovery/fleet/utils_test.go
  pkg/plugins/autodiscovery/helm/dependencies.go
  pkg/plugins/autodiscovery/helm/dockerimage.go
  pkg/plugins/autodiscovery/helm/dockerimage_test.go
  pkg/plugins/autodiscovery/helm/main.go
  pkg/plugins/autodiscovery/helm/main_test.go
  pkg/plugins/autodiscovery/helm/matchingRule.go
  pkg/plugins/autodiscovery/helm/testdata/chart/epinio/Chart.yaml
  pkg/plugins/autodiscovery/helm/testdata/chart/epinio/values.yaml
  pkg/plugins/autodiscovery/helm/utils.go
  pkg/plugins/autodiscovery/helm/utils_test.go
  pkg/plugins/utils/version/main.go
Labels: enhancement, experimental

#826 Fix: Autodiscovery groupBy correctly applied
  pkg/core/pipeline/autodiscovery/main.go
Labels: bug, autodiscovery

#823 Feat: [s][c][t] Add xml resource plugin
  e2e/updatecli.d/success.d/xml.yaml
  go.mod
  go.sum
  pkg/core/pipeline/resource/main.go
  pkg/plugins/resources/xml/changelog.go
  pkg/plugins/resources/xml/condition.go
  pkg/plugins/resources/xml/condition_test.go
  pkg/plugins/resources/xml/main.go
  pkg/plugins/resources/xml/source.go
  pkg/plugins/resources/xml/source_test.go
  pkg/plugins/resources/xml/spec.go
  pkg/plugins/resources/xml/target.go
  pkg/plugins/resources/xml/target_test.go
  pkg/plugins/resources/xml/testdata/bad_format_0.xml
  pkg/plugins/resources/xml/testdata/data_0.xml
  pkg/plugins/resources/xml/testdata/data_1.xml
  pkg/plugins/resources/xml/testdata/data_2.xml
Labels: enhancement, resource-xml

#834 Remove obsolete constant
  pkg/plugins/resources/xml/main.go
Labels: skip-changelog
