Repository updatecli/updatecli, pull requests merged in 2022-09, with the labels that each got.

#838 pullrequest correctly search linked targets based on pullrequestID
  e2e/updatecli.d/success.d/githubPullrequest.yaml
  pkg/core/pipeline/pullRequests.go
Labels: bug

#839 Fix: yaml source workdir relying on scm
  e2e/updatecli.d/success.d/githubPullrequest.yaml
  pkg/plugins/resources/yaml/source.go
Labels: bug

#832 Add new parameter "repositories" to Maven resource
  e2e/updatecli.d/success.d/maven.yaml
  e2e/updatecli.d/warning.d/maven.yaml
  pkg/plugins/resources/maven/condition.go
  pkg/plugins/resources/maven/condition_test.go
  pkg/plugins/resources/maven/main.go
  pkg/plugins/resources/maven/main_test.go
  pkg/plugins/resources/maven/source.go
  pkg/plugins/resources/maven/source_test.go
  pkg/plugins/resources/maven/utils.go
  pkg/plugins/resources/maven/utils_test.go
Labels: enhancement, resource-mavenrepository

#833 Feat: Add Autodiscovery for Maven dependencies
  e2e/updatecli.d/warning.d/autodiscovery/maven/git.yaml
  pkg/core/pipeline/autodiscovery/main.go
  pkg/plugins/autodiscovery/maven/dependency.go
  pkg/plugins/autodiscovery/maven/dependencyManagement.go
  pkg/plugins/autodiscovery/maven/main.go
  pkg/plugins/autodiscovery/maven/main_test.go
  pkg/plugins/autodiscovery/maven/matchingRule.go
  pkg/plugins/autodiscovery/maven/parentPomdependency.go
  pkg/plugins/autodiscovery/maven/pomSpec.go
  pkg/plugins/autodiscovery/maven/testdata/pom.xml
  pkg/plugins/autodiscovery/maven/utils.go
  pkg/plugins/autodiscovery/maven/utils_test.go
Labels: enhancement, resource-mavenrepository, autodiscovery

#853 Bump to Golangci 1.49 and fix linter issues
  .github/workflows/go.yaml
  .golangci.yml
  e2e/updatecli.d/success.d/githubPullrequest.yaml
  pkg/core/pipeline/autodiscovery/main.go
  pkg/core/reports/report.go
  pkg/core/transformer/main.go
  pkg/plugins/resources/helm/validate.go
  pkg/plugins/resources/shell/target.go
Labels: skip-changelog

#851 [updatecli] Bump Golang version to 1.19.1
  .github/workflows/go.yaml
  .github/workflows/release-sandbox.yaml
  .github/workflows/release.yaml
  .github/workflows/updatecli.yaml
  go.mod
Labels: chore

#857 Always use the latest Go version available when updating the go.mod from Updatecli GA
  .github/workflows/updatecli.yaml
  updatecli/updatecli.d/golang.yaml
Labels: skip-changelog

#845 fix: Support different XML path format
  e2e/updatecli.d/success.d/xml.yaml
  pkg/plugins/resources/xml/condition.go
  pkg/plugins/resources/xml/condition_test.go
  pkg/plugins/resources/xml/main.go
  pkg/plugins/resources/xml/source.go
  pkg/plugins/resources/xml/source_test.go
  pkg/plugins/resources/xml/target.go
  pkg/plugins/resources/xml/target_test.go
  pkg/plugins/resources/xml/utils.go
  pkg/plugins/resources/xml/utils_test.go
Labels: bug

#858 fix: Correctly retrieve GitHub enterprise url
  pkg/plugins/resources/githubrelease/main_test.go
  pkg/plugins/scms/github/changelog.go
  pkg/plugins/scms/github/changelog_test.go
  pkg/plugins/scms/github/main.go
  pkg/plugins/scms/github/main_test.go
  pkg/plugins/scms/github/scm.go
Labels: bug

#846 Fix: Various YAML file path scenario
  e2e/updatecli.d/success.d/yaml.yaml
  pkg/plugins/resources/yaml/condition.go
  pkg/plugins/resources/yaml/source.go
  pkg/plugins/resources/yaml/target.go
  pkg/plugins/resources/yaml/utils.go
  pkg/plugins/resources/yaml/utils_test.go
Labels: bug

#863 Add graphql path when creating client
  pkg/plugins/scms/github/main.go
Labels: bug, scm-github, pullrequest-github

#868 fix: Gitea pullrequest shouldn't try to be opened if missing remote branches
  pkg/plugins/resources/gitea/branch/main.go
  pkg/plugins/resources/gitea/pullrequest/create.go
  pkg/plugins/resources/gitea/pullrequest/create_test.go
  pkg/plugins/resources/gitea/pullrequest/main.go
  pkg/plugins/resources/gitea/pullrequest/main_test.go
  pkg/plugins/resources/gitea/pullrequest/utils.go
Labels: bug, gitea-pullrequest

#878 Add Helmfile autodiscovery crawler
  e2e/updatecli.d/warning.d/autodiscovery/helmfile/example.1.yaml
  pkg/core/pipeline/autodiscovery/main.go
  pkg/plugins/autodiscovery/helmfile/main.go
  pkg/plugins/autodiscovery/helmfile/main_test.go
  pkg/plugins/autodiscovery/helmfile/matchingRule.go
  pkg/plugins/autodiscovery/helmfile/releases.go
  pkg/plugins/autodiscovery/helmfile/testdata/helmfile.d/cik8s.yaml
  pkg/plugins/autodiscovery/helmfile/utils.go
  pkg/plugins/autodiscovery/helmfile/utils_test.go
Labels: autodiscovery

#877 No default crawler when autodiscovery is used with manifest
  e2e/updatecli.d/warning.d/autodiscovery/fleet/git.yaml
  e2e/updatecli.d/warning.d/autodiscovery/fleet/githubPullrequest.yaml
  e2e/updatecli.d/warning.d/autodiscovery/helm/example.1.yaml
  e2e/updatecli.d/warning.d/autodiscovery/maven/git.yaml
  pkg/core/pipeline/autodiscovery/main.go
  pkg/plugins/autodiscovery/fleet/main.go
  pkg/plugins/autodiscovery/helm/main.go
  pkg/plugins/autodiscovery/helmfile/main.go
  pkg/plugins/autodiscovery/maven/main.go
Labels: autodiscovery

#880 Remove example directory
  examples/scripts.d/env.sh
  examples/secrets.yaml
  examples/updatecli.d/docker-compose.yaml
  examples/updatecli.d/dockerfile.yaml
  examples/updatecli.d/grafana-loki.yaml
  examples/updatecli.d/jenkins-chart.yaml
  examples/updatecli.d/jenkins-wiki-exporter.yaml
  examples/updatecli.d/jenkins.yaml
  examples/updatecli.d/jenkinsio.yaml
  examples/updatecli.d/nginx.yaml
  examples/updatecli.d/noYamlConditionScm.yaml
  examples/updatecli.d/pluginsite-api.yaml
  examples/updatecli.d/prometheus.yaml
  examples/updatecli.d/shell.yaml
  examples/updatecli.d/sources/dockerfile_sources.yaml
  examples/updatecli.d/updatecli.yaml
  examples/updatecli.generic/LICENSE
  examples/updatecli.generic/aws_ami.yaml
  examples/updatecli.generic/dockerdigest.yaml
  examples/updatecli.generic/dockerfile/Dockerfile
  examples/updatecli.generic/dockerfile/dockerfile-coordinates.yaml
  examples/updatecli.generic/dockerfile/dockerfile-textmatcher.yaml
  examples/updatecli.generic/dockerimage.yaml
  examples/updatecli.generic/file.yaml
  examples/updatecli.generic/files.yaml
  examples/updatecli.generic/gitTag.yaml
  examples/updatecli.generic/githubRelease.yaml
  examples/updatecli.generic/helmChart/SCM.2.yaml
  examples/updatecli.generic/helmChart/SCM.deprecated.yaml
  examples/updatecli.generic/helmChart/noSCM.yaml
  examples/updatecli.generic/helmChart/requirement.yaml
  examples/updatecli.generic/helmRelease.yaml
  examples/updatecli.generic/jenkins.yaml
  examples/updatecli.generic/maven.yaml
  examples/updatecli.generic/runtimeTemplating.2.yaml
  examples/updatecli.generic/runtimeTemplating.yaml
  examples/updatecli.generic/shell/condition.sh
  examples/updatecli.generic/shell/shell.yaml
  examples/updatecli.generic/shell/source.sh
  examples/updatecli.generic/shell/target.sh
  examples/updatecli.generic/transformers/jenkins.yaml
  examples/updatecli.generic/yaml.yaml
  examples/values.yaml
Labels: skip-changelog

#882 fix: truncate pull request body
  pkg/plugins/scms/github/pullrequest.go
  pkg/plugins/utils/truncate/main.go
  pkg/plugins/utils/truncate/main_test.go
Labels: enhancement, pullrequest-github

#887 chore: don't make `sources.name` mandatory in JSON Schema
  pkg/core/pipeline/resource/main.go
Labels: ux

#886 Deprecate depends_on in favor of dependson
  e2e/updatecli.d/success.d/command.yaml
  pkg/core/pipeline/condition/main.go
  pkg/core/pipeline/resource/main.go
  pkg/core/pipeline/source/main.go
  pkg/core/pipeline/target/main.go
Labels: deprecated

#885 Add Json support
  e2e/updatecli.d/success.d/json.yaml
  go.mod
  go.sum
  pkg/core/pipeline/resource/main.go
  pkg/plugins/resources/json/changelog.go
  pkg/plugins/resources/json/condition.go
  pkg/plugins/resources/json/condition_test.go
  pkg/plugins/resources/json/main.go
  pkg/plugins/resources/json/source.go
  pkg/plugins/resources/json/source_test.go
  pkg/plugins/resources/json/spec.go
  pkg/plugins/resources/json/target.go
  pkg/plugins/resources/json/target_test.go
  pkg/plugins/resources/json/testdata/data.json
  pkg/plugins/resources/json/utils.go
  pkg/plugins/resources/json/utils_test.go
Labels: resource-json

#891 Add missing spec comment to json spec
  pkg/plugins/resources/json/spec.go
Labels: skip-changelog

#894 Add multiple query support to json resource
  pkg/plugins/resources/json/condition.go
  pkg/plugins/resources/json/condition_test.go
  pkg/plugins/resources/json/spec.go
  pkg/plugins/resources/json/target.go
  pkg/plugins/resources/json/target_test.go
  pkg/plugins/resources/json/testdata/data.json
Labels: skip-changelog, resource-json

#889 Add Toml support
  e2e/updatecli.d/success.d/toml.yaml
  pkg/core/pipeline/resource/main.go
  pkg/plugins/resources/toml/changelog.go
  pkg/plugins/resources/toml/condition.go
  pkg/plugins/resources/toml/condition_test.go
  pkg/plugins/resources/toml/main.go
  pkg/plugins/resources/toml/source.go
  pkg/plugins/resources/toml/source_test.go
  pkg/plugins/resources/toml/spec.go
  pkg/plugins/resources/toml/target.go
  pkg/plugins/resources/toml/target_test.go
  pkg/plugins/resources/toml/testdata/data.toml
  pkg/plugins/resources/toml/utils.go
  pkg/plugins/resources/toml/utils_test.go
Labels: resource-toml

#890 Add csv resource
  pkg/core/pipeline/resource/main.go
  pkg/plugins/resources/csv/changelog.go
  pkg/plugins/resources/csv/condition.go
  pkg/plugins/resources/csv/condition_test.go
  pkg/plugins/resources/csv/main.go
  pkg/plugins/resources/csv/source.go
  pkg/plugins/resources/csv/source_test.go
  pkg/plugins/resources/csv/spec.go
  pkg/plugins/resources/csv/target.go
  pkg/plugins/resources/csv/target_test.go
  pkg/plugins/resources/csv/testdata/data.2.csv
  pkg/plugins/resources/csv/testdata/data.csv
  pkg/plugins/resources/csv/utils.go
  pkg/plugins/resources/csv/utils_test.go
Labels: enhancement, resource-csv

#898 Cleanup Updatecli manifest
  updatecli/updatecli.d/golang.yaml
  updatecli/updatecli.d/golangci-lint.yaml
  updatecli/updatecli.d/updatecli.yaml
  updatecli/updatecli.d/venom.yaml
Labels: skip-changelog
