Repository updatecli/updatecli, pull requests merged in 2022-06, with the labels that each got.

#715 pkg/core/config: replace deprecated `strings.Title` with `cases.Title`
  pkg/core/config/main.go
Labels: cleanup

#717 fix(github) initialize the headbranch
  pkg/core/pipeline/main.go
  pkg/core/pipeline/scm/main.go
  pkg/plugins/scms/github/main.go
  pkg/plugins/scms/github/main_test.go
Labels: bug, scm-github

#732 fix: check if the extension is not `yaml` and not `yml`
  pkg/core/config/template.go
Labels: bug

#741 Bump containerd dependency to 1.6.6
  go.mod
  go.sum
Labels: dependencies
