Repository updatecli/updatecli, pull requests merged in 2022-07, with the labels that each got.

#746 fix: Report shouldn't show source and target if none were configured
  pkg/core/reports/main.go
Labels: bug, reports

#747 fix: Empty changelog message shouldn't display source object even in debug mode
  pkg/core/pipeline/source/main.go
Labels: bug

#713 feat(SCM) Introduces a "local" SCM with autoguessing
  Makefile
  e2e/updatecli.d/deprecated.d/transformers.yaml
  e2e/updatecli.d/skipped.targets.d/multiple-conditions.yaml
  e2e/updatecli.d/skipped.targets.d/one-condition.yaml
  e2e/updatecli.d/success.d/command.yaml
  e2e/updatecli.d/success.d/helmchart.yaml
  e2e/updatecli.d/success.d/jenkins.yaml
  e2e/updatecli.d/success.d/maven.yaml
  e2e/updatecli.d/success.d/source/gitTag.yaml
  e2e/updatecli.d/success.d/source/githubRelease.2.yaml
  e2e/updatecli.d/success.d/source/githubRelease.yaml
  e2e/updatecli.d/success.d/transformers.yaml
  e2e/values.yaml
  e2e/venom.d/test_deprecated.yaml
  e2e/venom.d/test_diff.yaml
  e2e/venom.d/test_skipped_targets.yaml
  go.mod
  go.sum
  pkg/core/config/defaults.go
  pkg/core/config/defaults_test.go
  pkg/core/config/errors.go
  pkg/core/config/main.go
  pkg/core/pipeline/scm/config.go
  pkg/core/pipeline/scm/config_test.go
  pkg/core/pipeline/scm/main.go
  pkg/core/pipeline/scm/mocks.go
  pkg/plugins/resources/gittag/condition.go
  pkg/plugins/resources/gittag/main.go
  pkg/plugins/resources/gittag/source.go
  pkg/plugins/resources/gittag/target.go
  pkg/plugins/scms/git/main.go
  pkg/plugins/scms/git/main_test.go
  pkg/plugins/scms/git/scm.go
  pkg/plugins/scms/github/main.go
  pkg/plugins/scms/github/main_test.go
  pkg/plugins/scms/github/pullrequest.go
  pkg/plugins/scms/github/scm.go
  pkg/plugins/utils/gitgeneric/main.go
  pkg/plugins/utils/gitgeneric/main_test.go
  pkg/plugins/utils/gitgeneric/mocks.go
Labels: enhancement

#756 Create add_issue_to_project.yaml
  .github/workflows/add_issue_to_project.yaml
Labels: skip-changelog

#754 feat: Allow to set environment variable within shell resources
  examples/scripts.d/env.sh
  examples/updatecli.d/shell.yaml
  pkg/plugins/resources/shell/command.go
  pkg/plugins/resources/shell/condition.go
  pkg/plugins/resources/shell/environment.go
  pkg/plugins/resources/shell/environments.go
  pkg/plugins/resources/shell/main.go
  pkg/plugins/resources/shell/main_test.go
  pkg/plugins/resources/shell/source.go
  pkg/plugins/resources/shell/target.go
Labels: enhancement, resource-shell

#764 Create codecov.yaml
  codecov.yaml
Labels: skip-changelog

#775 Add path env to golang updatecli manifest
  updatecli/updatecli.d/golang.yaml
Labels: skip-changelog

#782 Add use title for auto merge
  pkg/plugins/scms/github/pullrequest.go
Labels: enhancement, pullrequest-github

#790 Remove github dependency from jenkins plugin
  pkg/plugins/resources/jenkins/main.go
Labels: resource-jenkins, cleanup
