Repository updatecli/updatecli, pull requests merged in 2022-03, with the labels that each got.

#543 Test at runtime if a yaml file exists
  pkg/plugins/resources/yaml/condition.go
  pkg/plugins/resources/yaml/condition_test.go
  pkg/plugins/resources/yaml/main.go
  pkg/plugins/resources/yaml/main_test.go
  pkg/plugins/resources/yaml/source.go
  pkg/plugins/resources/yaml/target.go
Labels: bug

#548 Update oldest tag in gitgeneric test
  pkg/plugins/utils/gitgeneric/main_test.go
Labels: bug, skip-changelog

#544 chore(release-drafter) add documentation labels
  .github/release-drafter.yaml
Labels: skip-changelog

#551 Feat/capture Adding a parameter for the transformer FindSubMatch
  pkg/core/transformer/findSubMatch.go
  pkg/core/transformer/main.go
  pkg/core/transformer/main_test.go
Labels: enhancement, transformers

#555 Add another vanity metric
  README.adoc
Labels: skip-changelog

#557 Fix for Authentication Bug with Private Git Repos
  pkg/plugins/scms/git/scm.go
  pkg/plugins/scms/github/scm.go
  pkg/plugins/utils/gitgeneric/main.go
Labels: bug

#566 chore: add comment about the capturedIndex of findSubMatch
  pkg/core/transformer/main.go
Labels: skip-changelog

#563 Add Signing To Commit Function
  pkg/plugins/scms/git/main.go
  pkg/plugins/scms/git/scm.go
  pkg/plugins/scms/git/sign/main.go
  pkg/plugins/scms/git/sign/main_test.go
  pkg/plugins/scms/github/main.go
  pkg/plugins/scms/github/scm.go
  pkg/plugins/utils/gitgeneric/main.go
Labels: enhancement

#564 Resource "File" correctly uses scmID
  pkg/plugins/resources/file/source.go
  pkg/plugins/resources/file/source_test.go
Labels: bug, resource-file

#565 Improve reporting of pipeline with wrong configuration
  cmd/root.go
  pkg/core/config/main.go
  pkg/core/engine/main.go
Labels: enhancement

#584 fix(file) correct a regression when URL is used for source files
  pkg/plugins/resources/file/source.go
  pkg/plugins/resources/file/source_test.go
Labels: bug, resource-file

#592 cleanup(source) remove deprecated code for replacers
  pkg/core/pipeline/source/main.go
  pkg/core/pipeline/source/replacer.go
  pkg/core/pipeline/source/replacer_test.go
Labels: source, cleanup

#595 fix(docker*) do not show a warning when username and password are specified
  pkg/plugins/utils/docker/dockerregistry/main.go
Labels: bug, resource-dockerdigest, resource-docker

#596 chore(release-drafter) support labels `cleanup` and `deprecate` for patch version
  .github/release-drafter.yaml
Labels: skip-changelog

#588 fix(config) throw an error when a pullrequest specifies a non existing SCM
  pkg/core/config/main.go
  pkg/core/config/main_test.go
Labels: bug, cleanup

#590 cleanup(gittag, githubrelease) remove deprecated code for field `version`
  Makefile
  examples/updatecli.d/dockerfile.yaml
  examples/updatecli.d/jenkins-wiki-exporter.yaml
  examples/updatecli.d/pluginsite-api.yaml
  examples/updatecli.d/sources/dockerfile_sources.yaml
  examples/updatecli.d/updatecli.yaml
  pkg/core/pipeline/condition/main.go
  pkg/core/pipeline/scm/main.go
  pkg/core/pipeline/source/main.go
  pkg/core/pipeline/target/main.go
  pkg/plugins/resources/githubrelease/main.go
  pkg/plugins/resources/githubrelease/main_test.go
  pkg/plugins/resources/gittag/condition.go
  pkg/plugins/resources/gittag/main.go
  pkg/plugins/resources/gittag/source.go
  pkg/plugins/resources/gittag/target.go
  pkg/plugins/scms/git/scm.go
  pkg/plugins/scms/github/main.go
  pkg/plugins/scms/github/main_test.go
  pkg/plugins/scms/github/scm.go
  pkg/plugins/utils/version/main.go
  pkg/plugins/utils/version/main_test.go
Labels: resource-githubRelease, resource-gittag, cleanup

#589 cleanup(sources): remove deprecated syntax 'source:' (singular source)
  CONTRIBUTING.adoc
  examples/updatecli.d/docker-compose.yaml
  examples/updatecli.d/dockerfile.yaml
  examples/updatecli.d/grafana-loki.yaml
  examples/updatecli.d/jenkins-chart.yaml
  examples/updatecli.d/jenkins-wiki-exporter.yaml
  examples/updatecli.d/jenkins.yaml
  examples/updatecli.d/jenkinsio.yaml
  examples/updatecli.d/nginx.yaml
  examples/updatecli.d/noYamlConditionScm.yaml
  examples/updatecli.d/pluginsite-api.yaml
  examples/updatecli.d/prometheus.yalm
  examples/updatecli.d/updatecli.yaml
  examples/updatecli.generic/helmChart/SCM.deprecated.yaml
  examples/updatecli.generic/helmChart/noSCM.yaml
  examples/updatecli.generic/helmChart/requirement.yaml
  examples/updatecli.generic/helmRelease.yaml
  examples/updatecli.generic/transformers/jenkins.yaml
  pkg/core/config/main.go
  pkg/core/config/main_test.go
Labels: source, cleanup

#591 cleanup(pipeline) remove deprecated code for prefix and postfix
  CONTRIBUTING.adoc
  examples/updatecli.d/docker-compose.yaml
  examples/updatecli.d/jenkins.yaml
  examples/updatecli.d/updatecli.yaml
  pkg/core/pipeline/condition/main.go
  pkg/core/pipeline/conditions.go
  pkg/core/pipeline/resource/main.go
  pkg/core/pipeline/source/main.go
  pkg/core/pipeline/target/main.go
  pkg/core/pipeline/targets.go
Labels: transformers, cleanup

#608 chore: replace hardcoded ⚠
  pkg/core/pipeline/resource/main.go
Labels: chore, skip-changelog
