Repository updatecli/updatecli, pull requests merged in 2023-10, with the labels that each got.

#1646 chore(ADOPTERS): remove duplicated `k3s` entry
  ADOPTERS.md
Labels: documentation, chore, skip-changelog

#1648 fix: messages are not in correct order
  pkg/plugins/resources/json/target.go
Labels: bug, target, resource-json

#1605 Allow to share/reuse Updatecli manifest using any OCI registry
  .github/actions/spelling/allow.txt
  cmd/apply.go
  cmd/diff.go
  cmd/manifest_pull.go
  cmd/manifest_push.go
  cmd/manifest_show.go
  cmd/manifest_upgrade.go
  cmd/prepare.go
  cmd/root.go
  cmd/show.go
  go.mod
  go.sum
  pkg/core/config/main.go
  pkg/core/engine/autodiscovery.go
  pkg/core/engine/configuration.go
  pkg/core/engine/main.go
  pkg/core/engine/manifest_show.go
  pkg/core/engine/manifest_upgrade.go
  pkg/core/engine/options.go
  pkg/core/engine/prepare.go
  pkg/core/engine/registry.go
  pkg/core/engine/run.go
  pkg/core/engine/schema.go
  pkg/core/engine/scm.go
  pkg/core/engine/utils.go
  pkg/core/helpers/main.go
  pkg/core/registry/metadata.go
  pkg/core/registry/pull.go
  pkg/core/registry/pullpush_test.go
  pkg/core/registry/push.go
  pkg/core/registry/testdata/Policy.yaml
  pkg/core/registry/testdata/secrets.yaml
  pkg/core/registry/testdata/values.yaml
  pkg/core/registry/testdata/venom.yaml
  pkg/core/registry/utils.go
  pkg/core/registry/var.go
  pkg/core/text/main.go
Labels: enhancement

#1643 Add update compose command
  .github/actions/spelling/allow.txt
  cmd/apply.go
  cmd/compose.go
  cmd/compose_apply.go
  cmd/compose_diff.go
  cmd/compose_show.go
  cmd/diff.go
  cmd/jsonschema.go
  cmd/manifest_show.go
  cmd/manifest_upgrade.go
  cmd/prepare.go
  cmd/root.go
  cmd/show.go
  go.mod
  go.sum
  pkg/core/compose/env_files.go
  pkg/core/compose/environment.go
  pkg/core/compose/file.go
  pkg/core/compose/main.go
  pkg/core/compose/main_test.go
  pkg/core/compose/spec.go
  pkg/core/compose/testdata/credentials.yaml
  pkg/core/compose/testdata/update-compose.yaml
  pkg/core/engine/manifest/main.go
  pkg/core/engine/options.go
  pkg/core/engine/schema.go
  pkg/core/registry/pull.go
Labels: enhancement, update-compose

#1678 Group all go mod update
  .github/workflows/updatecli.yaml
  updatecli/updatecli.d/golang/minor.yaml
  updatecli/updatecli.d/golang/patch.yaml
Labels: skip-changelog

#1689 Update updatecli github action
  .github/workflows/updatecli.yaml
Labels: skip-changelog

#1687 chore: clean up Updatecli manifest
  updatecli/updatecli.d/golang/golang.yaml
  updatecli/updatecli.d/golang/major.yaml
  updatecli/updatecli.d/golang/minor.yaml
  updatecli/updatecli.d/golang/patch.yaml
  updatecli/updatecli.d/golangci-lint.yaml
  updatecli/updatecli.d/updatecli.yaml
  updatecli/updatecli.d/venom.yaml
Labels: enhancement

#1688 chore: remove time from generated markdown man pages
  cmd/docs.go
Labels: enhancement

#1693 chore: By default autodiscovery actionid should use the pipeline name
  pkg/core/engine/autodiscovery.go
Labels: enhancement, autodiscovery

#1695 fix: fallback to updatecli.yaml or updatecli.d if no manifest specified
  pkg/core/config/main.go
  pkg/core/engine/configuration.go
  pkg/core/engine/utils.go
Labels: bug

#1697 updatecli.d: golang/major.yaml
  updatecli/updatecli.d/golang/major.yaml
Labels: skip-changelog

#1705 various updatecli compose fixes
  cmd/manifest_push.go
  pkg/core/compose/main.go
  pkg/core/compose/spec.go
  pkg/core/engine/configuration.go
  pkg/core/engine/registry.go
  pkg/core/engine/utils.go
  pkg/core/registry/metadata.go
  pkg/core/registry/pull.go
  pkg/core/registry/pullpush_test.go
  pkg/core/registry/push.go
  pkg/core/registry/utils.go
Labels: bug, update-compose

#1712 feat: support for pinning docker digests by image config
  pkg/plugins/resources/dockerdigest/condition_test.go
  pkg/plugins/resources/dockerdigest/source.go
  pkg/plugins/resources/dockerdigest/source_test.go
  updatecli/updatecli.d/golang/major.yaml
  updatecli/updatecli.d/golang/minor.yaml
  updatecli/updatecli.d/golang/patch.yaml
Labels: resource-dockerdigest

#1721 fix: for muliple pipelines report failure to load
  pkg/core/engine/configuration.go
  pkg/core/engine/configuration_test.go
  pkg/core/engine/testdata/defaultManifestDirname_multiple/updatecli.d/test.yaml
  pkg/core/engine/testdata/defaultManifestDirname_multiple/updatecli.d/test2.yaml
  pkg/core/engine/testdata/defaultManifestDirname_multiple_failure/updatecli.d/failure.yaml
  pkg/core/engine/testdata/defaultManifestDirname_multiple_failure/updatecli.d/test.yaml
  pkg/core/engine/testdata/defaultManifestDirname_single/updatecli.d/test.yaml
  pkg/core/engine/testdata/defaultManifestFilename/updatecli.yaml
Labels: bug
