Repository updatecli/updatecli, pull requests merged in 2023-04, with the labels that each got.

#1245 Re-design pullrequest managed by Updatecli
  pkg/core/config/defaults.go
  pkg/core/pipeline/action/main.go
  pkg/core/pipeline/actions.go
  pkg/core/reports/action.go
  pkg/core/reports/actionTarget.go
  pkg/core/reports/action_test.go
  pkg/core/reports/actions.go
  pkg/core/reports/testdata/body.go
  pkg/core/reports/testdata/expectedBody.html
  pkg/plugins/resources/gitea/pullrequest/create.go
  pkg/plugins/resources/gitlab/mergerequest/create.go
  pkg/plugins/resources/stash/pullrequest/create.go
  pkg/plugins/scms/github/pullrequest.go
  pkg/plugins/utils/action/main.go
Labels: enhancement, pullrequest-github, pullrequest

#1275 Add hash return to gittag plugin
  pkg/plugins/resources/gittag/main.go
  pkg/plugins/resources/gittag/main_test.go
  pkg/plugins/resources/gittag/source.go
  pkg/plugins/resources/gittag/source_test.go
  pkg/plugins/utils/gitgeneric/main.go
  pkg/plugins/utils/gitgeneric/main_test.go
Labels: enhancement, resource-gittag, scm-gittea

#1279 Use default action title for autodiscovery using groupby all
  pkg/core/engine/main.go
Labels: enhancement

#1283 Use semver for default Golang version filtering
  pkg/plugins/resources/go/language/main.go
Labels: bug

#1284 fix golang autodiscovery matching rule
  pkg/plugins/autodiscovery/golang/matchingRule.go
  pkg/plugins/autodiscovery/golang/matchingRule_test.go
Labels: bug

#1289 Fix pipelineId generated for autodiscovery based on groupby
  pkg/core/engine/main.go
Labels: bug

#1294 Revert "Removing temporarly the minor manifest"
  updatecli/updatecli.d/golang/minor.yaml
Labels: skip-changelog

#1307 Reformat yaml comment
  pkg/plugins/resources/yaml/main.go
Labels: skip-changelog

#1311 Update gitlab mergerequest comment
  pkg/plugins/resources/gitlab/client/main.go
  pkg/plugins/resources/gitlab/client/spec.go
  pkg/plugins/resources/gitlab/mergerequest/main.go
  pkg/plugins/resources/gitlab/mergerequest/spec.go
Labels: skip-changelog
