Repository updatecli/updatecli, pull requests merged in 2023-08, with the labels that each got.

#1445 docs: fix pull request template test script
  .github/pull_request_template.md
Labels: skip-changelog

#1446 Add versionincrement setting to Helm autodiscovery
  e2e/updatecli.d/warning.d/autodiscovery/helm/example.versionfilter.yaml
  pkg/plugins/autodiscovery/helm/container.go
  pkg/plugins/autodiscovery/helm/containerManifest.go
  pkg/plugins/autodiscovery/helm/dependencies.go
  pkg/plugins/autodiscovery/helm/dependencyManifest.go
  pkg/plugins/autodiscovery/helm/main.go
  pkg/plugins/autodiscovery/helm/test/main_test.go
Labels: enhancement, autodiscovery, resource-helm

#1448 remove duplicated default value
  cmd/apply.go
  cmd/docs.go
Labels: bug

#1447 allow to merge multiple values/secret files
  .github/actions/spelling/allow.txt
  pkg/core/config/template.go
  pkg/core/config/template_test.go
Labels: bug

#1451 disable go mod caching
  .github/workflows/go.yaml
  .github/workflows/release.yaml
  .github/workflows/updatecli.yaml
Labels: skip-changelog

#1460 fix: handle non-existing cargo packages
  pkg/plugins/resources/cargopackage/condition_test.go
  pkg/plugins/resources/cargopackage/main.go
  pkg/plugins/resources/cargopackage/source_test.go
Labels: bug, resource-cargo

#1457 Support multiple manifest into one single file
  e2e/updatecli.d/success.d/multiManifest.yaml
  pkg/core/config/helper.go
  pkg/core/config/main.go
  pkg/core/config/main_test.go
  pkg/core/config/testdata/updatecli.d/badJenkins.yaml
  pkg/core/config/testdata/updatecli.d/jenkins.yaml
  pkg/core/config/testdata/updatecli.d/multiJenkins.yaml
  pkg/core/config/testdata/updatecli.d/multiTemplatedJenkins.tpl
  pkg/core/config/testdata/values.yaml
  pkg/core/engine/main.go
Labels: enhancement

#1458 Add various go template function from helm
  pkg/core/config/funcsHelm.go
  pkg/core/config/funcsHelm_test.go
  pkg/core/config/funcsUpdatecli.go
  pkg/core/config/main.go
  pkg/core/config/template.go
Labels: enhancement

#1463 Allow Updatecli manifest/values to use JSON file
  e2e/updatecli.d/success.d/npm.json
  pkg/core/config/main.go
  pkg/core/config/main_test.go
  pkg/core/config/template.go
  pkg/core/config/testdata/updatecli.d/jenkins.json
  pkg/core/config/testdata/values.json
Labels: enhancement

#1464 Add Docker Image Tag to Docker Image Digest
  .github/actions/spelling/allow.txt
  e2e/updatecli.d/success.d/dockerdigest.yaml
  pkg/plugins/resources/dockerdigest/condition.go
  pkg/plugins/resources/dockerdigest/condition_test.go
  pkg/plugins/resources/dockerdigest/main.go
  pkg/plugins/resources/dockerdigest/source.go
  pkg/plugins/resources/dockerdigest/source_test.go
  pkg/plugins/resources/dockerdigest/target.go
  pkg/plugins/utils/docker/main.go
Labels: enhancement, resource-dockerdigest

#1466 Re-word xml comment used for jsonschema
  .github/actions/spelling/allow.txt
  pkg/plugins/resources/xml/main.go
  pkg/plugins/resources/xml/source.go
  pkg/plugins/resources/xml/spec.go
Labels: documentation, resource-xml

#1467 Refactor helm documentation
  pkg/plugins/resources/helm/main.go
  pkg/plugins/utils/docker/main.go
Labels: documentation, resource-helm

#1470 Show templating diff from `updatecli manifest show --debug`
  cmd/manifest_show.go
  pkg/core/config/main.go
  pkg/core/config/variables.go
  pkg/core/text/main.go
  pkg/plugins/resources/file/condition.go
  pkg/plugins/resources/file/target.go
Labels: ux

#1474 By default use target name for commit message
  pkg/core/pipeline/target/main.go
Labels: target

#1473 Show file plugin target diff by default
  pkg/plugins/resources/file/target.go
Labels: resource-file, ux

#1476 Improve scm comments
  pkg/plugins/scms/git/commit/main.go
  pkg/plugins/scms/git/main.go
  pkg/plugins/scms/git/sign/main.go
  pkg/plugins/scms/gitea/main.go
  pkg/plugins/scms/github/main.go
  pkg/plugins/scms/gitlab/main.go
  pkg/plugins/scms/gitlab/scm.go
  pkg/plugins/scms/gitlab/util.go
  pkg/plugins/scms/stash/main.go
Labels: documentation, scm-github, scm-git, scm-gittea, scm-gitlab, scm-stash

#1503 Run go mod tidy
  go.sum
Labels: skip-changelog

#1485 Set default autodiscovery groupby to all
  .github/actions/spelling/allow.txt
  pkg/core/engine/main.go
  pkg/core/pipeline/autodiscovery/config.go
  pkg/core/pipeline/autodiscovery/groupby.go
  pkg/core/pipeline/autodiscovery/main.go
Labels: enhancement, autodiscovery

#1512 Update Golang module github.com/go-git/go-git/v5
  go.mod
  go.sum
Labels: dependencies

#1508 Update Golang module github.com/drone/go-scm
  go.mod
  go.sum
Labels: dependencies

#1516 Update Golang module golang.org/x/text
  go.mod
  go.sum
Labels: dependencies

#1514 Update Golang module golang.org/x/oauth2
  go.mod
  go.sum
Labels: dependencies

#1519 Update Golang module golang.org/x/mod
  go.mod
  go.sum
Labels: dependencies

#1522 Update Golang module github.com/aws/aws-sdk-go
  go.mod
  go.sum
Labels: dependencies

#1521 Update Golang module helm.sh/helm/v3
  go.mod
  go.sum
Labels: dependencies

#1525 Updatecli golang manifest
  updatecli/updatecli.d/golang/minor.yaml
  updatecli/updatecli.d/golang/patch.yaml
Labels: skip-changelog

#1526 by default disable Helm autodiscovery version increment
  pkg/plugins/autodiscovery/helm/main.go
  pkg/plugins/autodiscovery/helm/test/main_test.go
Labels: enhancement, autodiscovery, resource-helm

#1537 Clean up GitLab mergerquest plugin
  pkg/plugins/resources/gitlab/client/spec.go
  pkg/plugins/resources/gitlab/mergerequest/create.go
  pkg/plugins/resources/gitlab/mergerequest/main.go
  pkg/plugins/resources/gitlab/mergerequest/spec.go
  pkg/plugins/resources/gitlab/mergerequest/utils.go
Labels: skip-changelog, scm-gitlab

#1544 Update golangci-lint installation method
  .github/workflows/go.yaml
Labels: skip-changelog
