Repository updatecli/updatecli, pull requests merged in 2023-12, with the labels that each got.

#1815 chore(helmfile): remove useless error message
  pkg/plugins/autodiscovery/helmfile/releases.go
Labels: bug

#1822 deps: rename and bump github.com/getsops/sops/v3
  .github/actions/spelling/allow.txt
  go.mod
  go.sum
  pkg/core/config/template.go
Labels: dependencies

#1825 chore: only run updatecli on targeted branch main
  .github/workflows/updatecli.yaml
Labels: chore

#1814 feat(autodiscovery): move autodiscovery out of experimental
  .github/actions/spelling/allow.txt
  .github/workflows/go.yaml
  e2e/updatecli.d/success.d/autodiscovery/cargo/example.1.yaml
  e2e/updatecli.d/success.d/autodiscovery/cargo/kubewarden.versionfilter.yaml
  e2e/updatecli.d/success.d/autodiscovery/cargo/kubewarden.yaml
  e2e/updatecli.d/success.d/autodiscovery/docker-compose/example.1.yaml
  e2e/updatecli.d/success.d/autodiscovery/docker-compose/example.2.yaml
  e2e/updatecli.d/success.d/autodiscovery/docker-compose/example.3.yaml
  e2e/updatecli.d/success.d/autodiscovery/docker-compose/example.4.yaml
  e2e/updatecli.d/success.d/autodiscovery/dockerfile/asciidoctor.yaml
  e2e/updatecli.d/success.d/autodiscovery/dockerfile/epinio.yaml
  e2e/updatecli.d/success.d/autodiscovery/dockerfile/jenkins-infra.yaml
  e2e/updatecli.d/success.d/autodiscovery/dockerfile/versionfilter.yaml
  e2e/updatecli.d/success.d/autodiscovery/fleet/git.yaml
  e2e/updatecli.d/success.d/autodiscovery/fleet/githubPullrequest.yaml
  e2e/updatecli.d/success.d/autodiscovery/golang/golangOnly.yaml
  e2e/updatecli.d/success.d/autodiscovery/golang/minorOnly.yaml
  e2e/updatecli.d/success.d/autodiscovery/golang/patchOnly.yaml
  e2e/updatecli.d/success.d/autodiscovery/helm/example.1.yaml
  e2e/updatecli.d/success.d/autodiscovery/helm/example.versionfilter.yaml
  e2e/updatecli.d/success.d/autodiscovery/helmfile/example.1.yaml
  e2e/updatecli.d/success.d/autodiscovery/maven/git.yaml
  e2e/updatecli.d/success.d/autodiscovery/npm/npm.versionfilter.yaml
  e2e/updatecli.d/success.d/autodiscovery/npm/npm.yaml
  e2e/updatecli.d/success.d/autodiscovery/updatecli/git.yaml
  pkg/core/engine/autodiscovery.go
  pkg/plugins/autodiscovery/dockerfile/errors.go
  pkg/plugins/autodiscovery/dockerfile/utils.go
  pkg/plugins/autodiscovery/dockerfile/utils_test.go
  pkg/plugins/resources/dockerimage/spec.go
Labels: enhancement, autodiscovery

#1831 Fix comment that break the generated doc
  pkg/plugins/resources/file/main.go
Labels: documentation

#1832 fix: yamlpath with searchpattern always return changed
  pkg/plugins/resources/yaml/target.go
Labels: bug, resource-yaml

#1838 feat(helm): Helm Autodiscovery ignore local dependencies
  pkg/plugins/autodiscovery/helm/dependencies.go
  pkg/plugins/autodiscovery/helm/test/testdata-3/chart/sample/Chart.yaml
Labels: enhancement, autodiscovery, resource-helm

#1841 feat(scm): add BasicAuth to stash
  pkg/plugins/resources/stash/client/main.go
Labels: enhancement
