Repository updatecli/updatecli, pull requests merged in 2023-05, with the labels that each got.

#1303 perf: Add mutex guard to github functions for concurrent safety
  pkg/plugins/scms/github/changelog.go
  pkg/plugins/scms/github/main.go
Labels: enhancement, github_actions

#1318 reference embedded field directly
  pkg/core/pipeline/condition/main.go
  pkg/core/pipeline/source/main.go
  pkg/core/pipeline/target/main.go
Labels: cleanup

#1316 chore: more compact footer template
  pkg/plugins/utils/action/main.go
Labels: chore, pullrequest, actions

#1324 awsami source correctly handles if not filter
  pkg/plugins/resources/awsami/data_test.go
  pkg/plugins/resources/awsami/source.go
Labels: skip-changelog

#1337 Correctly handled target execution result
  pkg/core/pipeline/target/main.go
Labels: bug

#1338 Fix yaml plugin regression
  pkg/plugins/resources/yaml/target.go
Labels: bug

#1347 #1346: Implement the support for registry in the autodiscovery feature for helm
  pkg/plugins/autodiscovery/helm/container.go
  pkg/plugins/autodiscovery/helm/containerManifest.go
  pkg/plugins/autodiscovery/helm/dependencies.go
  pkg/plugins/autodiscovery/helm/test/main_test.go
  pkg/plugins/autodiscovery/helm/test/testdata-1/chart/epinio/Chart.yaml
  pkg/plugins/autodiscovery/helm/test/testdata-1/chart/epinio/values.yaml
  pkg/plugins/autodiscovery/helm/test/testdata-2/chart/sample/Chart.yaml
  pkg/plugins/autodiscovery/helm/test/testdata-2/chart/sample/values.yaml
  pkg/plugins/autodiscovery/helm/test/testdata-3/chart/sample/Chart.yaml
  pkg/plugins/autodiscovery/helm/test/testdata-3/chart/sample/values.yaml
  pkg/plugins/autodiscovery/helm/utils_test.go
Labels: enhancement, autodiscovery, resource-helm
