Repository updatecli/updatecli, pull requests merged in 2023-07, with the labels that each got.

#1405 fix: goreleaser deprecation
  .goreleaser.yml
  Makefile
Labels: skip-changelog

#1407 fix(gittag) ensure `gittag` targets does not fail due to (unspecified) version filters
  .gitignore
  e2e/updatecli.d/success.d/gitTag.yaml
  e2e/updatecli.d/success.d/gittag.yaml
  pkg/plugins/resources/gittag/target.go
  pkg/plugins/utils/version/errors.go
  pkg/plugins/utils/version/filter.go
  pkg/plugins/utils/version/filter_test.go
  pkg/plugins/utils/version/semver.go
Labels: bug, target, resource-gittag

#1410 Automate cosign instruction update
  updatecli/updatecli.d/updatecli.yaml
Labels: skip-changelog

#1344 Add Updatecli integration with Udash
  .github/actions/spelling/allow.txt
  cmd/apply.go
  cmd/diff.go
  cmd/login.go
  cmd/root.go
  go.mod
  go.sum
  pkg/core/auth/config.go
  pkg/core/auth/helpers.go
  pkg/core/auth/login.go
  pkg/core/auth/main.go
  pkg/core/auth/token.go
  pkg/core/pipeline/main.go
  pkg/core/pipeline/target/main.go
  pkg/core/reports/main.go
  pkg/core/reports/publish.go
  pkg/core/reports/report.go
  pkg/core/result/condition.go
  pkg/core/result/scm.go
  pkg/core/result/source.go
  pkg/core/result/target.go
  pkg/plugins/resources/csv/target.go
  pkg/plugins/resources/dockerfile/target.go
  pkg/plugins/resources/file/target.go
  pkg/plugins/resources/gitbranch/target.go
  pkg/plugins/resources/gitea/release/target.go
  pkg/plugins/resources/gitlab/release/target.go
  pkg/plugins/resources/gittag/target.go
  pkg/plugins/resources/go/gomod/target.go
  pkg/plugins/resources/json/target.go
  pkg/plugins/resources/shell/target.go
  pkg/plugins/resources/stash/release/target.go
  pkg/plugins/resources/toml/target.go
  pkg/plugins/resources/xml/target.go
  pkg/plugins/resources/yaml/target.go
Labels: enhancement, experimental

#1419 Pin golang autodiscovery e2e tests
  e2e/updatecli.d/warning.d/autodiscovery/golang/golangOnly.yaml
  e2e/updatecli.d/warning.d/autodiscovery/golang/minorOnly.yaml
  e2e/updatecli.d/warning.d/autodiscovery/golang/patchOnly.yaml
Labels: skip-changelog

#1426 Fix condition report by using the correct variable
  pkg/core/pipeline/conditions.go
  pkg/core/pipeline/sources.go
  pkg/core/pipeline/targets.go
Labels: bug, reports

#1424 feat: add hcl resource plugin
  .github/actions/spelling/allow.txt
  e2e/updatecli.d/success.d/hcl/noscm.yaml
  e2e/updatecli.d/success.d/hcl/scm.yaml
  go.mod
  go.sum
  pkg/core/pipeline/resource/main.go
  pkg/plugins/resources/hcl/condition.go
  pkg/plugins/resources/hcl/condition_test.go
  pkg/plugins/resources/hcl/main.go
  pkg/plugins/resources/hcl/main_test.go
  pkg/plugins/resources/hcl/source.go
  pkg/plugins/resources/hcl/source_test.go
  pkg/plugins/resources/hcl/spec.go
  pkg/plugins/resources/hcl/spec_test.go
  pkg/plugins/resources/hcl/target.go
  pkg/plugins/resources/hcl/target_test.go
  pkg/plugins/resources/hcl/testdata/data.hcl
Labels: enhancement, target, source, condition, resource-hcl

#1418 Add Updatecli integration with Udash Part 2
  cmd/apply.go
  cmd/diff.go
  cmd/docs.go
  cmd/login.go
  cmd/root.go
  cmd/udash.go
  cmd/udash_config.go
  cmd/udash_login.go
  cmd/udash_logout.go
  go.mod
  go.sum
  pkg/core/pipeline/condition/main.go
  pkg/core/pipeline/main.go
  pkg/core/pipeline/source/main.go
  pkg/core/pipeline/target/main.go
  pkg/core/reports/report.go
  pkg/core/result/condition.go
  pkg/core/result/source.go
  pkg/core/result/target.go
  pkg/core/udash/config_spec.go
  pkg/core/udash/env.go
  pkg/core/udash/helpers.go
  pkg/core/udash/login.go
  pkg/core/udash/logout.go
  pkg/core/udash/main.go
  pkg/core/udash/oauthInfo.go
  pkg/core/udash/publish.go
  pkg/core/udash/token.go
Labels: experimental, udash

#1433 Tidy Up go.mod
  go.mod
  updatecli/updatecli.d/golang/major.yaml
  updatecli/updatecli.d/golang/minor.yaml
  updatecli/updatecli.d/golang/patch.yaml
Labels: skip-changelog

#1436 Fix Udash login flow with access_token
  pkg/core/udash/config_spec.go
  pkg/core/udash/main.go
Labels: bug, experimental, udash

#1439 Fix udash login when config doesn' exist yet
  pkg/core/udash/config_spec.go
Labels: bug, experimental, udash
