Repository updatecli/updatecli, pull requests merged in 2024-09, with the labels that each got.

#2601 feat(core): implement retry client for http fetching
  .github/actions/spelling/expect.txt
  pkg/core/text/main.go
  pkg/core/text/main_test.go
  pkg/plugins/utils/http/client.go
Labels: enhancement

#2567 feat: implement prow autodiscovery
  .github/actions/spelling/allow.txt
  e2e/updatecli.d/success.d/autodiscovery/prow/prow.yaml
  pkg/core/pipeline/autodiscovery/main.go
  pkg/plugins/autodiscovery/kubernetes/containers.go
  pkg/plugins/autodiscovery/kubernetes/kubernetes.go
  pkg/plugins/autodiscovery/kubernetes/kubernetesSpec.go
  pkg/plugins/autodiscovery/kubernetes/main.go
  pkg/plugins/autodiscovery/kubernetes/manifestTemplate.go
  pkg/plugins/autodiscovery/kubernetes/podSpec.go
  pkg/plugins/autodiscovery/kubernetes/prow.go
  pkg/plugins/autodiscovery/kubernetes/prowSpec.go
  pkg/plugins/autodiscovery/kubernetes/test/main_test.go
  pkg/plugins/autodiscovery/kubernetes/test/testdata/prow/prow.yaml
  pkg/plugins/autodiscovery/kubernetes/utils.go
  pkg/plugins/autodiscovery/kubernetes/utils_test.go
Labels: enhancement, prow

#2632 chore(spelling): add end of line new line
  .github/actions/spelling/excludes.txt
  .github/actions/spelling/patterns.txt
Labels: skip-changelog

#2689 chore: update golang patch one at a time
  updatecli/values.d/golang_patch.yaml
Labels: skip-changelog

#2737 fix(prow/e2e): ignore broken image and use updatecli-test
  e2e/updatecli.d/success.d/autodiscovery/prow/prow.yaml
Labels: skip-changelog

#2736 Fix prerelease semver filtering when current version is stable
  pkg/plugins/utils/version/filter.go
  pkg/plugins/utils/version/filter_test.go
Labels: bug
