Repository updatecli/updatecli, pull requests merged in 2024-04, with the labels that each got.

#2018 Allow to recreate working branch based on their "base" branch
  pkg/core/pipeline/action/main.go
  pkg/core/pipeline/actions.go
  pkg/core/pipeline/main.go
  pkg/core/pipeline/scm/main.go
  pkg/core/pipeline/sources.go
  pkg/core/pipeline/target/main.go
  pkg/core/result/scm.go
  pkg/plugins/resources/gitea/pullrequest/create.go
  pkg/plugins/resources/gitea/pullrequest/main.go
  pkg/plugins/resources/gitlab/mergerequest/create.go
  pkg/plugins/resources/stash/pullrequest/create.go
  pkg/plugins/resources/stash/pullrequest/main.go
  pkg/plugins/scms/git/main.go
  pkg/plugins/scms/git/scm.go
  pkg/plugins/scms/gitea/main.go
  pkg/plugins/scms/gitea/scm.go
  pkg/plugins/scms/github/main.go
  pkg/plugins/scms/github/pullrequest.go
  pkg/plugins/scms/github/scm.go
  pkg/plugins/scms/gitlab/main.go
  pkg/plugins/scms/gitlab/scm.go
  pkg/plugins/scms/stash/main.go
  pkg/plugins/scms/stash/scm.go
  pkg/plugins/utils/gitgeneric/branch.go
  pkg/plugins/utils/gitgeneric/main.go
Labels: enhancement, scm-github, scm-git, scm-gittea, scm-gitlab, scm-stash, core

#2021 feat: close GitHub pullrequest when no file changed
  .github/actions/spelling/allow.txt
  _typos.toml
  pkg/core/pipeline/action/main.go
  pkg/core/pipeline/actions.go
  pkg/core/pipeline/sort.go
  pkg/core/pipeline/target/main.go
  pkg/core/reports/actions.go
  pkg/plugins/resources/gitea/pullrequest/clean.go
  pkg/plugins/resources/gitlab/mergerequest/clean.go
  pkg/plugins/resources/stash/pullrequest/clean.go
  pkg/plugins/scms/github/comment.go
  pkg/plugins/scms/github/pullrequest.go
Labels: enhancement, github_actions

#2026 feat: By default scm github/gitlab/stash/gitea uses force push
  pkg/plugins/scms/git/main.go
  pkg/plugins/scms/gitea/main.go
  pkg/plugins/scms/gitea/scm.go
  pkg/plugins/scms/github/main.go
  pkg/plugins/scms/github/main_test.go
  pkg/plugins/scms/github/scm.go
  pkg/plugins/scms/gitlab/main.go
  pkg/plugins/scms/gitlab/scm.go
  pkg/plugins/scms/stash/main.go
  pkg/plugins/scms/stash/scm.go
Labels: enhancement

#2027 ci: override updatecli version used in GH
  .github/workflows/updatecli.yaml
Labels: skip-changelog

#2031 Run updatecli workflow every hour
  .github/workflows/updatecli.yaml
Labels: skip-changelog

#2033 fix: updatecli autodiscovery only matching rule
  pkg/plugins/autodiscovery/updatecli/policies.go
Labels: bug, autodiscovery

#2036 chore: sort reports by results
  pkg/core/engine/run.go
  pkg/core/reports/main.go
  pkg/core/reports/main_test.go
Labels: enhancement, ux

#2040 fix: execute actions once all pipelines have been executed
  pkg/core/engine/actions.go
  pkg/core/engine/reports.go
  pkg/core/engine/run.go
  pkg/core/engine/udash.go
  pkg/core/pipeline/actions.go
  pkg/core/pipeline/main.go
  pkg/plugins/scms/github/pullrequest.go
Labels: bug, core

#2044 deps: bump updatecli to v0.76.0-rc.1
  .github/workflows/updatecli.yaml
Labels: skip-changelog

#2047 fix: Restrict update-compose.yaml to automate update
  updatecli/values.d/update-compose.yaml
Labels: skip-changelog

#2046 feat: Add support for GitHub API commit
  .github/actions/spelling/allow.txt
  .github/actions/spelling/patterns.txt
  pkg/plugins/scms/github/main.go
  pkg/plugins/scms/github/mocks.go
  pkg/plugins/scms/github/pullrequest.go
  pkg/plugins/scms/github/scm.go
  pkg/plugins/scms/github/scm_test.go
  pkg/plugins/utils/fileoperations.go
  pkg/plugins/utils/fileoperations_test.go
  pkg/plugins/utils/filepath_test.go
  pkg/plugins/utils/gitgeneric/main.go
  pkg/plugins/utils/gitgeneric/main_test.go
Labels: enhancement, scm-github

#2054 fix: execute actions once all pipelines have been executed (part 2)
  pkg/core/engine/actions.go
  pkg/core/pipeline/actions.go
  pkg/core/pipeline/target/main.go
Labels: bug

#2057 fix: always try to update existing pullrequest description
  pkg/core/pipeline/actions.go
  pkg/plugins/scms/github/pullrequest.go
Labels: bug

#2059 deps: bump updatecli workflow to 0.76.0-rc.4
  .github/workflows/updatecli.yaml
Labels: skip-changelog

#2060 feat: gomod plugin allow http,https,file scheme
  pkg/plugins/resources/go/gomod/condition_test.go
  pkg/plugins/resources/go/gomod/main.go
  pkg/plugins/resources/go/gomod/source.go
  pkg/plugins/resources/go/gomod/source_test.go
  pkg/plugins/resources/go/gomod/spec.go
  pkg/plugins/resources/go/gomod/version.go
Labels: enhancement, go/module

#2061 feat: gomod allow to check module existence only
  pkg/plugins/resources/go/gomod/condition.go
  pkg/plugins/resources/go/gomod/condition_test.go
Labels: enhancement, go/module

#2070 fix: use API for creating branch and fetching hashes when committing using Github API
  pkg/plugins/scms/github/main.go
  pkg/plugins/scms/github/scm.go
Labels: bug

#2076 fix: several github api commit fixes
  .github/actions/spelling/allow.txt
  .github/actions/spelling/patterns.txt
  pkg/plugins/scms/github/pullrequest.go
  pkg/plugins/scms/github/scm.go
Labels: bug, pullrequest-github, skip-changelog

#2079 chore: removing version pinning in updatecli workflow
  .github/workflows/updatecli.yaml
Labels: skip-changelog
