Repository updatecli/updatecli, pull requests merged in 2024-08, with the labels that each got.

#2415 feat: allow to use boolean operator in target dependson value
  pkg/core/pipeline/dependsOn.go
  pkg/core/pipeline/dependsOn_test.go
  pkg/core/pipeline/sort.go
  pkg/core/pipeline/target_test.go
  pkg/core/pipeline/targets.go
Labels: enhancement

#2438 fix: golang autodiscovery with module only
  pkg/plugins/autodiscovery/golang/dependency.go
  pkg/plugins/autodiscovery/golang/matchingRule.go
Labels: bug, go

#2473 Update: Add additional semver patterns to comments
  pkg/plugins/autodiscovery/argocd/main.go
Labels: documentation

#2480 doc: Improve README and Contributing
  .github/actions/spelling/allow.txt
  CONTRIBUTING.adoc
  README.adoc
Labels: documentation, skip-changelog

#2530 fix: action log message when using invalid action kind
  pkg/core/pipeline/action/main.go
Labels: bug, ux, actions

#2529 Git SCM: Ignore missing action handler
  pkg/core/pipeline/actions.go
Labels: bug

#2556 feat(temurin) introduces a new source of type "Temurin"
  .github/actions/spelling/allow.txt
  e2e/updatecli.d/success.d/temurin/sources.yaml
  pkg/core/pipeline/resource/main.go
  pkg/plugins/resources/temurin/api.go
  pkg/plugins/resources/temurin/condition.go
  pkg/plugins/resources/temurin/condition_test.go
  pkg/plugins/resources/temurin/main.go
  pkg/plugins/resources/temurin/main_test.go
  pkg/plugins/resources/temurin/source.go
  pkg/plugins/resources/temurin/source_test.go
  pkg/plugins/resources/temurin/spec.go
  pkg/plugins/resources/temurin/target.go
  pkg/plugins/resources/temurin/types.go
  pkg/plugins/resources/updateclihttp/main.go
Labels: enhancement, temurin

#2576 fix: gitlab merge requests error
  go.mod
  go.sum
  pkg/plugins/resources/gitlab/client/main.go
Labels: bug, scm-gitlab

#2593 chore(gitlab tests) more restrictive main regex
  e2e/updatecli.d/success.d/githubRelease.yaml
  pkg/plugins/resources/gitlab/branch/source_test.go
Labels: chore
